import Head from "next/head";
import { PostCard, PostWidget, Categories, PostsCarousel } from "../components";
import { getPosts } from "../services";

export default function Home({ posts }) {
	return (
		<div className="container mx-auto px-10 mb-8">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{/* <PostsCarousel /> */}

			<div className="grid drid-cols lg:grid-cols-12 gap-12 ">
				<div className="lg:col-span-8 col-span-1">
					{/* {posts.map((post, index) => (
						<PostCard post={post.node} key={index} />
					))} */}
				</div>
				<div className="lg:col-span-4 col-span-1 mt-2">
					<div className="lg:sticky relative top-10">
						{/* <PostWidget />
						<Categories /> */}
					</div>
				</div>
			</div>
		</div>
	);
}

export async function getStaticProps() {
	const posts = (await getPosts()) || [];
	return {
		props: { posts },
	};
}
